"""
Django settings for goods_transportation_system project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR represents the root directory of your project. It's used to build paths for the project.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# This section provides quick configuration settings for development, not production.

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY is a unique, unpredictable value used by Django for cryptographic signing. Keep it secret in production.
SECRET_KEY = 'django-insecure-l41q-w45j)6=dy6o*=q@t%6!4@r99wj7%q2u0e4w-e30qam6@l'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG mode is used for development and testing only. Never use DEBUG=True in production as it exposes sensitive information.
DEBUG = True

# A list of strings representing the host/domain names that this Django site can serve.
# ALLOWED_HOSTS should be set to the domain names of your site in production for security reasons.
ALLOWED_HOSTS = []


# Application definition
# INSTALLED_APPS is a list of all Django applications and third-party apps that are activated in this project.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'transport',  
]

# MIDDLEWARE is a list of middleware components to use. Middleware is a way to process requests globally before they reach the view.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT_URLCONF is the Python path to the URL configuration module (urls.py) that Django uses.
ROOT_URLCONF = 'goods_transportation_system.urls'

# TEMPLATES is a list of template engines and options for template rendering. 
# The default setup is Django Templates with context processors.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS defines the directories to search for templates outside of app directories.
        
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,  # APP_DIRS tells Django to look for templates in the 'templates' directory of each installed app.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'transport.context_processors.is_host',
            ],
        },
    },
]



# WSGI_APPLICATION is the path to the WSGI application object that Django’s built-in servers use.
WSGI_APPLICATION = 'goods_transportation_system.wsgi.application'


# Database configuration
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# DATABASES is a dictionary that defines the database connection information.
DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.mysql',  
        'NAME': 'goods_transportation_db',  
        'USER': 'root',  
        'PASSWORD': '12345',  
        'HOST': 'localhost',  
        'PORT': '3306',  
    }
}

# AUTH_USER_MODEL specifies the custom user model for the project.
AUTH_USER_MODEL = 'transport.CustomUser'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS is a list of validators that are used to validate user passwords.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization settings
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# LANGUAGE_CODE is the language code for this installation. (e.g., 'en-us' for U.S. English).
LANGUAGE_CODE = 'en-us'

# TIME_ZONE is the time zone for this installation. (e.g., 'UTC' for Coordinated Universal Time).
TIME_ZONE = 'UTC'

# USE_I18N is a boolean that specifies if Django’s translation system should be enabled.
USE_I18N = True

# USE_TZ is a boolean that specifies if timezone-aware datetimes should be used.
USE_TZ = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# STATIC_URL is the URL to use when referring to static files (CSS, JavaScript, Images).
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

LOGIN_REDIRECT_URL = '/customer_dashboard/'
LOGIN_REDIRECT_URL = '/host_dashboard/'
LOGIN_URL = '/login/'

LOGOUT_REDIRECT_URL = '/'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
# DEFAULT_AUTO_FIELD specifies the default type of primary key to use for models that don’t specify a primary key.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


  




